// <auto-generated />
using System;
using Gestion_vuelos.src.Shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_vuelos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414033824_tipodocumento")]
    partial class tipodocumento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gestion_vuelos.src.Modules.Aerolineas.infrastructure.Entity.AerolineasEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("CodigoIata")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CodigoIata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("Pais_Origen_Id")
                        .HasColumnType("char(64)")
                        .HasColumnName("Country_Origen_Id");

                    b.HasKey("Id");

                    b.HasIndex("Pais_Origen_Id");

                    b.ToTable("airlines", (string)null);
                });

            modelBuilder.Entity("Gestion_vuelos.src.Modules.Aeropuerto.infrastructure.Entity.AeropuertoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Ciudad_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Ciudad_Id");

                    b.Property<string>("CodigoIata")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CodigoIata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Ciudad_Id");

                    b.ToTable("airport", (string)null);
                });

            modelBuilder.Entity("Gestion_vuelos.src.Modules.Ciudades.infrastructure.Entity.CiudadesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("PaisesId")
                        .HasColumnType("char(64)")
                        .HasColumnName("Country_id");

                    b.HasKey("Id");

                    b.HasIndex("PaisesId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Gestion_vuelos.src.Modules.Paises.infrastructure.Entity.PaisesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("codigoIso");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIso")
                        .IsUnique();

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("Gestion_vuelos.src.Modules.TipoDocumento.infrastructure.Entity.TipoDocumentoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("DocumentType", (string)null);
                });

            modelBuilder.Entity("Gestion_vuelos.src.Modules.Aerolineas.infrastructure.Entity.AerolineasEntity", b =>
                {
                    b.HasOne("Gestion_vuelos.src.Modules.Paises.infrastructure.Entity.PaisesEntity", "Paises")
                        .WithMany()
                        .HasForeignKey("Pais_Origen_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paises");
                });

            modelBuilder.Entity("Gestion_vuelos.src.Modules.Aeropuerto.infrastructure.Entity.AeropuertoEntity", b =>
                {
                    b.HasOne("Gestion_vuelos.src.Modules.Ciudades.infrastructure.Entity.CiudadesEntity", "Ciudades")
                        .WithMany()
                        .HasForeignKey("Ciudad_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Gestion_vuelos.src.Modules.Ciudades.infrastructure.Entity.CiudadesEntity", b =>
                {
                    b.HasOne("Gestion_vuelos.src.Modules.Paises.infrastructure.Entity.PaisesEntity", "Paises")
                        .WithMany()
                        .HasForeignKey("PaisesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paises");
                });
#pragma warning restore 612, 618
        }
    }
}
